#!/bin/bash

if [ -z "$2" ]; then
    exit 1;
else
    if [ "$2" = "down" ]; then
        echo "nameserver 208.67.222.222" > /etc/resolv.conf
        echo "nameserver 208.67.220.220" >> /etc/resolv.conf
        echo "nameserver 8.8.8.8" >> /etc/resolv.conf
        echo "nameserver 8.8.4.4" >> /etc/resolv.conf
    fi
fi
