#!/bin/sh
set -e

case "$2" in
up)
	/sbin/ifup $1
	echo "nameserver 208.67.222.222" > /etc/resolv.conf
	echo "nameserver 208.67.220.220" >> /etc/resolv.conf
	echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	echo "nameserver 8.8.4.4" >> /etc/resolv.conf
	;;
down)
	/sbin/ifdown $1
	echo "nameserver 208.67.222.222" > /etc/resolv.conf
	echo "nameserver 208.67.220.220" >> /etc/resolv.conf
	echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	echo "nameserver 8.8.4.4" >> /etc/resolv.conf
	;;
esac
