#!/bin/bash

./build.sh iso
mv voyage-current.iso ../voyage-ugent.iso

./build.sh tar
mv voyage-current.tar.bz2 ../voyage-ugent.tar.bz2

cd ..
tar cvjf voyage-ugent-config.tar.bz2 voyage-build-config/config voyage-build-config/build.sh voyage-build-config/build
md5sum voyage-ugent.iso voyage-ugent.tar.bz2 voyage-ugent-config.tar.bz2 > MD5SUMS
