#!/bin/bash

# Build iso image
./build.sh iso 2>&1 | tee build_iso.log
mv voyage-current.iso ../voyage-ugent.iso

# Build tar image
./build.sh tar 2>&1 | tee build_tar.log
mv voyage-current.tar.bz2 ../voyage-ugent.tar.bz2

# Move build logs
mv build_*.log ../

# Tar up configuration
cd ..
tar cvjf voyage-ugent-config.tar.bz2 voyage-build-config/config \
    voyage-build-config/build.sh voyage-build-config/autobuild
cd -

# Compute md5 hashes
cd ..
md5sum voyage-ugent* > MD5SUMS
cd -
