#!/bin/bash

DATE=`wget -S  "http://www.google.com/" -O- 2>&1 | grep -E '^[[:space:]]*[dD]ate:' | sed 's/^[[:space:]]*[dD]ate:[[:space:]]*//' | head -1l | awk '{print $1, $3, $2,  $5 ,"GMT", $4 }' | sed 's/,//'`

if [ "$DATE" != "" ]; then
    date -s "$DATE"
fi
