#!/bin/sh

#apt-get install voyage-util
export DEBIAN_FRONTEND=noninteractive 
DEBIAN_FRONTEND=noninteractive apt-get -q=2 -y install --force-yes voyage-util

update-rc.d -f rmnologin remove 

update-rc.d voyage-util defaults 99
update-rc.d ssh-phone-home defaults 97 02

#export DEBIAN_FRONTEND=noninteractive
#DEBIAN_FRONTEND=noninteractive apt-get -q=2 --yes --force-yes install voyage-util

cat /etc/motd.voyage >> /etc/motd.tail

#################################
# Modifying /etc/motd for build date
#################################
echo -n "Modifying /etc/motd for build date... "

sed -i -e "s/%versio/`date +%Y.%m`/; s/%buildda/`date +%Y%m%d`/" /etc/motd.tail

echo "Done"

touch voyage.1st

wget http://de.voyage.hk/dists/experimental/archive.key -O - | apt-key add - 

