==============================================================================
     __      __
     \ \    / /
      \ \  / /___  _   _  __ _  __ _  ___       Built upon Voyage,
       \ \/ // _ \| | | |/ _  |/ _  |/ _ \      a Debian GNU/Linux
        \  /| |_| | |_| | |_| | |_| |  __/      derivative for ALIX.
         \/  \___/ \__  |\__ _|\__  |\___|      http://linux.voyage.hk
                    __/ |       __/ |
                   |___/       |___/   _  _____            _
                                 | |  | |/ ____|          | |
                                 | |  | | |  __  ___ _ __ | |_
                                 | |  | | | |_ |/ _ \ '_ \| __|
                                 | |__| | |__| |  __/ | | | |_
                                  \____/ \_____|\___|_| |_|\__|


  1. PXE Boot Voyage UGent with a login shell
  2. Start automated install for WRAP (/dev/hda and 38400 serial console)
  3. Start automated install for ALIX (/dev/hda and 38400 serial console)
  4. Start automated install for 45/48xx (/dev/hda and 19200 serial console)
  5. Start automated install for 55xx (/dev/hda and 19200 serial console)
  6. Start automated install for generic PC (/dev/hda and no serial console)

==============================================================================
